import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from '@vercel/analytics/next';

import "./globals.css";
import Nav from "@/Layout/Nav";
import Footer from "@/Layout/Footer";
import Wrapper from "@/components/Layout/Wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog Genius",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <Wrapper>
          <Nav />
          <div className="bg-[#f7f7f7]">
            {children}
            <Analytics />
          </div>
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
